# Generated by Django 3.2.8 on 2021-12-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('desc', models.TextField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.category')),
            ],
        ),
    ]
