# Generated by Django 3.2.8 on 2022-01-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0004_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
